openapi: "3.0.0"
info:
  version: "0.2"
  title: Tallii API
paths:
  /api/v1/login:
    post:
      operationId: login,
      description: Logs a user in if the provided credentials are correct.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentials'
      responses:
        200:
          description: The jwt token for the session of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        400:
          description: The provided login credentials are not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/signup:
    post:
      operationId: signup,
      description: Logs a user in if the provided credentials are correct.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupCredentials'
      responses:
        200:
          description: The jwt token for the session of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        400:
          description: The provided invite code is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/invite-codes/{invite_code}:
    get:
      operationId: checkInviteCode,
      description: Checks if the provided invite code is valid and not taken.
      parameters:
        - name: invite_code
          in: path
          required: true
          description: The invite_code to check.
          schema:
            type: string
      responses:
        200:
          description: The provided invite_code is valid
        400:
          description: The provided invite code is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/users/{user_id}:
    get:
      operationId: getUser
      description: Gets a user with the user_id provided in the url.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The user_id of the user of the user.
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: The user that matches the provided user_id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/users/check-email/{email}:
    get:
      operationId: checkEmail
      description: Checks if the provided email is taken.
      parameters:
        - name: email
          in: path
          required: true
          description: The email to check.
          schema:
            type: string
            format: email
      responses:
        200:
          description: The email is not taken.
        400:
          description: The email is taken.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/users/check-username/{username}:
    get:
      operationId: checkUsername
      description: Checks if the provided username is taken.
      parameters:
        - name: username
          in: path
          required: true
          description: The username to check.
          schema:
            type: string
      responses:
        200:
          description: The username is not taken.
        400:
          description: The username is taken.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/friends:
    get:
      operationId: getFriends
      description: Gets the friends matching the provided user_id and status.
      parameters:
        - name: user_id
          in: query
          required: true
          description: The user_id to get friends for.
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: The friends that match the provided query params.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/me/friends:
    get:
      operationId: getMeFriends
      description: Gets the friends matching the provided status for the currently logged in user.
      parameters:
        - name: status
          in: query
          required: false
          description: The status of the friendship.
          schema:
            type: string
            enum: [pending, accepted, blocked]
      responses:
        200:
          description: The friends that match the provided query params.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: postMeFriends
      description: Sends, accepts, cancels, or denies a friend request given the provided query params.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int32
                operation:
                  type: string
                  enum:
                    - send_request
                    - accept_request
                    - cancel_request
                    - deny_request
      responses:
        200:
          description: The requested operation has completed.
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/events:
    get:
      operationId: getEvents
      description: Gets all events that match the provided query params.
      parameters:
        - name: user_id
          in: query
          required: true
          description: The user_id to get events for.
          schema:
            type: integer
            format: int32
        - name: player_status
          in: query
          required: false
          description: The player status of the user in the event.
          schema:
            type: string
            enum: [ pending, accepted, declined ]
      responses:
        200:
          description: The events that match the provided query params.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        500:
          description: An internal server error has occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      description: An error has occurred.
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    Event:
      description: An event.
      type: object
      required:
        - event_id
        - name
        - description
        - creator_user_id
        - created_at
      properties:
        event_id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
          nullable: true
        creator_user_id:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
    Friend:
      description: A friend of the currently logged in user.
      type: object
      required:
        - user_id
        - username
        - avatar
        - taunt
        - created_at
      properties:
        user_id:
          type: integer
          format: int32
        username:
          type: string
        avatar:
          type: string
          nullable: true
        taunt:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
    LoginCredentials:
      description: The body of the login request.
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    SignupCredentials:
      description: The body of the signup request request.
      type: object
      required:
        - email
        - username
        - password
        - invite_code
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        invite_code:
          type: string
        password:
          type: string
          format: password
    Token:
      description: A jwt token.
      type: object
      required:
        - token
      properties:
        token:
          type: string
    User:
      description: A person that is logged in to tallii.
      type: object
      required:
        - user_id
        - avatar
        - email
        - invite_code
        - username
        - taunt
        - verified
      properties:
        user_id:
          type: integer
          format: int32
        avatar:
          type: string
          nullable: true
        email:
          type: string
          format: email
        invite_code:
          type: string
        username:
          type: string
        taunt:
          type: string
          nullable: true
        verified:
          type: boolean
          nullable: true
