
version: "3.7"
services:
  database:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=tallii
      - POSTGRES_PASSWORD=tallii
      - POSTGRES_DB=tallii
    ports:
      - 7777:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:



# psql --host=database --username=tallii --dbname=tallii