### Get All Invite Codes

GET {{baseUrl}}/api/v1/invite-codes HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json


### Check Invite Codes

GET {{baseUrl}}/api/v1/invite-codes/mBZoPP HTTP/1.1
content-type: application/json

### Create new Invite Codes

POST {{baseUrl}}/api/v1/invite-codes HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "amount": 20
}

### Sign user up
POST {{baseUrl}}/api/v1/signup HTTP/1.1
content-type: application/json

{
    "email": "adam.aho@hey.com",
    "invite_code": "aho",
    "password": "password",
    "username": "adamaho"
}

### Sign user up
POST {{baseUrl}}/api/v1/signup HTTP/1.1
content-type: application/json

{
  "email": "bryanne@gmail.com",
  "invite_code": "mBZoPP",
  "password": "password",
  "username": "bryanne"
}

### Log user in
POST {{baseUrl}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "adam.aho@hey.com",
    "password": "password"
}

### checkUsername
GET {{baseUrl}}/api/v1/users/check-username/adamaho HTTP/1.1
content-type: application/json

### checkEmail
GET {{baseUrl}}/api/v1/users/check-email/adam.aho@hey.com HTTP/1.1
content-type: application/json

### getUserByUsername
GET {{baseUrl}}/api/v1/users/adamaho HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getMe
GET {{baseUrl}}/api/v1/me HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### followUser
PUT {{baseUrl}}/api/v1/me/follow/bryanne HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### unfollowUser
DELETE {{baseUrl}}/api/v1/me/following/bryanne HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getMeFollowers
GET {{baseUrl}}/api/v1/me/followers HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getMeFollowing
GET {{baseUrl}}/api/v1/me/following HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getUserFollowers
GET {{baseUrl}}/api/v1/users/bryanne/followers HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getUserFollowing
GET {{baseUrl}}/api/v1/users/bryanne/following HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getMeEvents
GET {{baseUrl}}/api/v1/me/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### createEvent
POST {{baseUrl}}/api/v1/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "name": "My Event",
  "description": "This is the description of the event",
  "members": [2]
}

### getEvent
GET {{baseUrl}}/api/v1/events/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### updateEvent
PATCH {{baseUrl}}/api/v1/events/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "name": "Adam's Event",
  "description": "This is a better description"
}

### deleteEvent
DELETE {{baseUrl}}/api/v1/events/4 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getMeEventInvitations
GET {{baseUrl}}/api/v1/me/events/invitations HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getMeEventInvitations
GET {{baseUrl}}/api/v1/me/events/invitations HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getEventMembers
GET {{baseUrl}}/api/v1/events/5/members HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### inviteEventMember
POST {{baseUrl}}/api/v1/events/5/invitations HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "user_id": 2
}

### updateEventMember
PATCH {{baseUrl}}/api/v1/events/5/members/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "role": "member",
  "state": "active"
}

### removeEventMember
DELETE {{baseUrl}}/api/v1/events/5/members/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### getEventTeams
GET {{baseUrl}}/api/v1/events/6/teams HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### createEventTeam
POST {{baseUrl}}/api/v1/events/6/teams HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "name": "Team 1",
  "members": [1]
}

