@baseUrl = http://localhost:8000

GET {{baseUrl}}/auth/invite-codes HTTP/1.1
content-type: application/json

###

POST {{baseUrl}}/auth/invite-codes HTTP/1.1
content-type: application/json

{
    "id": "vIw5sms"
}

###

POST {{baseUrl}}/auth/invite-codes/new HTTP/1.1
content-type: application/json

{
    "amount": 20
}

###

POST {{baseUrl}}/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "adam.aho@heqy.com",
    "invite_code": "naomU~",
    "password": "password",
    "username": "adam.ahqo"
}

###

POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{}