@baseUrl = http://localhost:8000

### Get All Invite Codes

GET {{baseUrl}}/api/v1/invite-codes HTTP/1.1
content-type: application/json

### Check Invite Codes

POST {{baseUrl}}/api/v1/invite-codes HTTP/1.1
content-type: application/json

{
    "id": "IVllaj"
}

### Create new Invite Codes

POST {{baseUrl}}/api/v1/invite-codes/new HTTP/1.1
content-type: application/json

{
    "amount": 20
}

### Sign user up

POST {{baseUrl}}/api/v1/signup HTTP/1.1
content-type: application/json

{
    "email": "foo2@bar.com",
    "invite_code": "KK_DUz",
    "password": "password",
    "username": "foo2.bar"
}

### Log user in

POST {{baseUrl}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "foo@bar.com",
    "password": "password"
}