### Get My Events
GET {{baseUrl}}/api/v1/me/events HTTP/1.1
Authorization: Bearer {{token}}

### Get Events for User
GET {{baseUrl}}/api/v1/events?user_id=2 HTTP/1.1
Authorization: Bearer {{token}}

### Get Specific Event
GET {{baseUrl}}/api/v1/events/1 HTTP/1.1
Authorization: Bearer {{token}}

### Create Event
POST {{baseUrl}}/api/v1/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "name": "My New Event",
  "description": "the best event ever",
  "players": [2]
}