### Get Events
GET {{baseUrl}}/api/v1/events?group_id=2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Get Events Teams
GET {{baseUrl}}/api/v1/events/1/teams HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Get Events Members
GET {{baseUrl}}/api/v1/events/1/members HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Create Event
POST {{baseUrl}}/api/v1/groups/2/events HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "event": {
    "name": "My New Event",
    "description": "the best event ever",
    "event_type": "individual"
  },
  "teams": [
    {
      "team": {
        "name": "Team 1"
      },
      "members": [
        {
          "user_id": 1
        },
        {
          "user_id": 3
        }
      ]
    },
    {
      "team": {
        "name": "Team 2"
      },
      "members": [
        {
          "user_id": 2
        },
        {
          "user_id": 4
        }
      ]
    }
  ]
}