@baseUrl = http://localhost:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiZm9vMi5iYXIiLCJleHAiOjE2MDA2NDg3NDN9.d-m2D-6W8QaligqXU0Rvm07PF1I75Fj-KM20DHdTVRg

### Get Groups

GET {{baseUrl}}/api/v1/groups HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Create Group
POST {{baseUrl}}/api/v1/groups HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Group 1",
    "description": "This is the description of the group"
}