@baseUrl = http://localhost:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiZm9vLmJhciIsImV4cCI6MTYwMTE1Mjk2OH0.lP_zzmhlcG3R7k8hYprg98hza_6EK5glM7GUk1nS1ug

### Get Groups

GET {{baseUrl}}/api/v1/groups HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Create Group
POST {{baseUrl}}/api/v1/groups HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Group 120",
    "description": "This is the description of the group",
    "members": [
        {
            "user_id": 1,
            "user_type": "owner"
        }
    ]
}