### Get Players
GET {{baseUrl}}/api/v1/players?event_id=1 HTTP/1.1
Authorization: Bearer {{token}}


### Update Player Status
PUT {{baseUrl}}/api/v1/players/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "status": "pending"
}