### Get All Invite Codes

GET {{baseUrl}}/api/v1/invite-codes HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Check Invite Codes

POST {{baseUrl}}/api/v1/invite-codes HTTP/1.1
content-type: application/json

{
    "id": "IVllaj"
}

### Create new Invite Codes

POST {{baseUrl}}/api/v1/invite-codes HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "amount": 20
}

### Sign user up

POST {{baseUrl}}/api/v1/signup HTTP/1.1
content-type: application/json

{
    "email": "bryanne@gmail.com",
    "invite_code": "EXqNWd",
    "password": "password",
    "username": "bryanne"
}

### Log user in

POST {{baseUrl}}/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "bryanne@gmail.com",
    "password": "password"
}