use actix_web::web;

use crate::services::{events, friends, users};

pub fn define_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/invite-codes")
            .route(web::post().to(users::handlers::check_invite_code))
            .route(web::get().to(users::handlers::get_all_invite_codes)),
    )
    .service(
        web::resource("/invite-codes/new")
            .route(web::post().to(users::handlers::create_invite_codes)),
    )
    .service(
        web::resource("/users/check-username")
            .route(web::post().to(users::handlers::check_username)),
    )
    .service(
        web::resource("/users/check-email").route(web::post().to(users::handlers::check_email)),
    )
    .service(
        web::resource("/users/check-email").route(web::post().to(users::handlers::check_email)),
    )
    .service(web::resource("/users/{user_id}").route(web::get().to(users::handlers::get_user)))
    .service(web::resource("/users").route(web::get().to(users::handlers::search_users)))
    .service(web::resource("/login").route(web::post().to(users::handlers::login)))
    .service(web::resource("/signup").route(web::post().to(users::handlers::signup)))
    .service(web::resource("/friends").route(web::get().to(friends::handlers::get_friends)))
    .service(
        web::resource("/friends/invitations")
            .route(web::get().to(friends::handlers::get_friend_invitations)),
    )
    .service(
        web::resource("/friends/requests")
            .route(web::get().to(friends::handlers::get_friend_requests))
            .route(web::post().to(friends::handlers::send_friend_request)),
    )
    .service(
        web::resource("/friends/requests/cancel")
            .route(web::post().to(friends::handlers::cancel_friend_request)),
    )
    .service(
        web::resource("/friends/requests/deny")
            .route(web::post().to(friends::handlers::deny_friend_request)),
    )
    .service(
        web::resource("/friends/requests/accept")
            .route(web::post().to(friends::handlers::accept_friend_request)),
    )
    .service(
        web::resource("/events")
            .route(web::get().to(events::handlers::get_events))
            .route(web::post().to(events::handlers::create)),
    )
    .service(web::resource("/events/{event_id}").route(web::get().to(events::handlers::get_event)))
    .service(
        web::resource("/events/{event_id}/participants")
            .route(web::get().to(events::handlers::get_event_participants)),
    )
    .service(
        web::resource("/events/{event_id}/participants/{event_participant_id}")
            .route(web::put().to(events::handlers::update_event_participant)),
    )
    .service(
        web::resource("/events/{event_id}/teams")
            .route(web::get().to(events::handlers::get_event_teams))
            .route(web::post().to(events::handlers::create_event_team)),
    )
    .service(
        web::resource("/events/{event_id}/teams/participants")
            .route(web::get().to(events::handlers::get_event_team_participants))
    );
}
